# Generated by Django 4.0.3 on 2022-03-24 01:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Domicilio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('active', models.BooleanField(default=True)),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo')),
                ('nombre', models.CharField(max_length=500)),
                ('latitud', models.CharField(max_length=500, verbose_name='latitud')),
                ('longitud', models.CharField(max_length=500, verbose_name='logitud')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to=None, verbose_name='iamgen')),
                ('telefono', models.IntegerField(verbose_name='Telefono')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Domicilio',
                'verbose_name_plural': 'Domicilios',
            },
        ),
    ]
